// <auto-generated/>
namespace UI.Layers
{
	public static class LayerType
	{
		public const string MARKERS = "Markers";
		public const string POPOVERS = "Popovers";
		public const string POPUPS = "Popups";
		public const string SCREENS = "Screens";
		public const string WINDOWS = "Windows";
	}
}